### ISSUE TITLE
Tutorial webpage points to a file that is not in the github repo

### ISSUE THREAD

**Issue by shruthivis** [salilab/actin_tutorial#3]
https://integrativemodeling.org/tutorials/actin/analysis.html  mentions a `plot_stat.py` in the scripts folder which is missing from this github repo.

**Comment by benmwebb** [comment]
Yes, I noticed this when I was reviewing the text for the website. A fix is in the works: the [imp-sampcon repo](https://github.com/salilab/imp-sampcon) has a suitable script and I [merged it into IMP](https://github.com/salilab/imp/commit/04bfca0da)  this week. It'll be in the next IMP release, due out this month, at which point I'll update the actin tutorial to use it.

**Comment by benmwebb** [comment]
Fixed by 15e2765168.
