### ISSUE TITLE
Error using the SAXS restraint

### ISSUE THREAD

**Issue by shruthivis** [salilab/actin_tutorial#4]
Running modeling.py with the latest IMP release (2.13) returns an error
"Module isd2 not installed. Cannot use SAXSISDRestraint"
This is because the SAXS restraint in PMI (`saxs.py`) imports the module isd2 which is not found in IMP 2.13. All references to isd2 probably need to be fixed.

**Comment by benmwebb** [comment]
That's not an error; it's just telling you that you can't use `SAXSISDRestraint`. The actin tutorial doesn't use that restraint anyway, so you're good.

**Comment by shruthivis** [comment]
Ok, closed!
