### ISSUE TITLE
Model precision criteria need to be updated to reflect the current implementation of imp-sampcon

### ISSUE THREAD

**Issue by neeleshsoni21** [salilab/actin_tutorial#5]
This issue is a follow-up from the imp-sampcon [issue #39](https://github.com/salilab/imp-sampcon/issues/39). The model precision determination criteria in [analysis.md](https://github.com/salilab/actin_tutorial/blob/main/doc/analyis.md) in section "**Results for sampling exhaustiveness protocol...** panel (C) caption" needs to be updated as explained here in [issue #39](https://github.com/salilab/imp-sampcon/issues/39). Additionally, if possible, it would useful to highlight this minor update (compare to the BJ 2017 paper) in the tutorial text.

**Comment by benmwebb** [comment]
@neeleshsoni21 Feel free to update the text accordingly (you likely have the best understanding of the criteria). You should have write access already.

**Comment by neeleshsoni21** [comment]
I have changed the tutorial text with the updated definitions.
